openapi: 3.0.3
info:
  title: openapi-string-byte-schema
  version: 0.0.1

paths:
  /error:
    post:
      security:
        - microservice_auth:
            - USER:GET
      responses:
        200:
          description: Content.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    microservice_auth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: "http://authorize.com/oauth/token/"
          scopes:
            "USER:GET": "User GET"
            "ADMIN:POST": "Admin POST"
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
          format: byte
