openapi: 3.0.3
info:
  title: openapi-string-byte-schema
  version: 0.0.1

paths:
  /error:
    post:
      responses:
        200:
          description: Content.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
          format: byte